"""add missing listing fields

Revision ID: 0c766926c2e0
Revises: 27d91cb25429
Create Date: 2025-12-30 16:45:25.126775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c766926c2e0'
down_revision: Union[str, Sequence[str], None] = '27d91cb25429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    op.add_column('listings', sa.Column('crop_id', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('ai_price_status', sa.String(length=50), nullable=True))
    op.add_column('listings', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('ai_price_direction', sa.String(length=50), nullable=True))
    op.add_column('listings', sa.Column('ai_market_message', sa.String(length=500), nullable=True))
    op.add_column('listings', sa.Column('region_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'region_id')
    op.drop_column('listings', 'ai_market_message')
    op.drop_column('listings', 'ai_price_direction')
    op.drop_column('listings', 'ai_confidence')
    op.drop_column('listings', 'ai_price_status')
    op.drop_column('listings', 'crop_id')
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    # ### end Alembic commands ###
