"""Add successful_transactions to buyers

Revision ID: 5fa46e1b41eb
Revises: 0c766926c2e0
Create Date: 2026-01-26 20:41:17.555222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fa46e1b41eb'
down_revision: Union[str, Sequence[str], None] = '0c766926c2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS audit_logs')
    op.add_column('buyers', sa.Column(
        'successful_transactions', sa.Integer(), nullable=True))
    op.add_column('buyers', sa.Column(
        'failed_transactions', sa.Integer(), nullable=True))
    op.add_column('buyers', sa.Column(
        'average_response_time_min', sa.Float(), nullable=True))
    op.add_column('buyers', sa.Column('risk_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buyers', 'risk_score')
    op.drop_column('buyers', 'average_response_time_min')
    op.drop_column('buyers', 'failed_transactions')
    op.drop_column('buyers', 'successful_transactions')
    op.create_table('audit_logs',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('actor_user_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('action', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=True),
                    sa.Column('entity_type', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=True),
                    sa.Column('entity_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('ip_address', sa.VARCHAR(length=45),
                              autoincrement=False, nullable=True),
                    sa.Column('user_agent', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('description', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
                    )
    # ### end Alembic commands ###
