"""added buyer_requests table

Revision ID: 63203e6ee5e5
Revises: 4597917747e6
Create Date: 2026-01-27 15:32:25.516343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63203e6ee5e5'
down_revision: Union[str, Sequence[str], None] = '4597917747e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('crop_type', sa.String(), nullable=False),
    sa.Column('required_kg', sa.Float(), nullable=False),
    sa.Column('preferred_district', sa.String(), nullable=False),
    sa.Column('max_price_per_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_requests_id'), 'buyer_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buyer_requests_id'), table_name='buyer_requests')
    op.drop_table('buyer_requests')
    # ### end Alembic commands ###
