"""add image_url to listings

Revision ID: bd6f6fc1ea12
Revises: efbbd8d4790f
Create Date: 2025-12-28 22:17:39.977920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6f6fc1ea12'
down_revision: Union[str, Sequence[str], None] = 'efbbd8d4790f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'image_url')
    # ### end Alembic commands ###
