"""initial schema

Revision ID: efbbd8d4790f
Revises: 
Create Date: 2025-12-27 21:52:41.684121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efbbd8d4790f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('FARMER', 'BUYER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('buyer_type', sa.Enum('INDIVIDUAL', 'WHOLESALER', 'RETAILER', 'HOTEL_RESTAURANT', 'EXPORTER', 'PROCESSOR', name='buyertype'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('fraud_score', sa.Float(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_districts', sa.String(length=500), nullable=True),
    sa.Column('base_district', sa.String(length=100), nullable=False),
    sa.Column('base_latitude', sa.Float(), nullable=True),
    sa.Column('base_longitude', sa.Float(), nullable=True),
    sa.Column('min_purchase_qty_kg', sa.Float(), nullable=True),
    sa.Column('max_purchase_qty_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_buyers_base_district'), 'buyers', ['base_district'], unique=False)
    op.create_index(op.f('ix_buyers_id'), 'buyers', ['id'], unique=False)
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('farm_size_hectares', sa.Float(), nullable=True),
    sa.Column('main_crops', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_farmers_district'), 'farmers', ['district'], unique=False)
    op.create_index(op.f('ix_farmers_id'), 'farmers', ['id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('crop_type', sa.String(length=100), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('asking_price', sa.Float(), nullable=False),
    sa.Column('ai_suggested_price', sa.Float(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'MATCHED', 'SOLD', 'EXPIRED', 'CANCELLED', name='listingstatus'), nullable=False),
    sa.Column('harvest_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_crop_type'), 'listings', ['crop_type'], unique=False)
    op.create_index(op.f('ix_listings_district'), 'listings', ['district'], unique=False)
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INTERESTED', 'ACCEPTED', 'REJECTED', 'COMPLETED', 'EXPIRED', name='matchstatus'), nullable=False),
    sa.Column('is_notified_farmer', sa.Boolean(), nullable=True),
    sa.Column('is_notified_buyer', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_TRANSIT', 'COMPLETED', 'CANCELLED', 'DISPUTED', name='transactionstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PARTIAL', 'PAID', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('delivery_note', sa.String(length=500), nullable=True),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_district'), table_name='listings')
    op.drop_index(op.f('ix_listings_crop_type'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_farmers_id'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_district'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_buyers_id'), table_name='buyers')
    op.drop_index(op.f('ix_buyers_base_district'), table_name='buyers')
    op.drop_table('buyers')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
