from typing import Optional
from datetime import datetime
from pydantic import BaseModel, Field, ConfigDict, HttpUrl, field_validator
from ..models.listing import ListingStatus

# ------------------------------------------------------------------
# SHARED PROPERTIES
# ------------------------------------------------------------------
class ListingBase(BaseModel):
    """
    Base properties for a crop listing.
    Ensures consistent data validation for both creation and updates.
    """
    crop_type: str = Field(..., example="Maize", description="Type of crop being sold")
    crop_id: int = Field(..., example=1, description="The ID of the crop from the crops table")
    quantity_kg: float = Field(..., gt=0, example=500.0, description="Quantity in Kilograms")
    district: str = Field(..., example="Musanze")
    sector: Optional[str] = Field(None, example="Kinigi")
    harvest_date: Optional[datetime] = Field(None, description="Expected or actual harvest date")
    image_url: Optional[str] = Field(None, example="https://example.com/image.jpg")

    @field_validator("image_url", mode="before")
    @classmethod
    def validate_image_url(cls, v):
        # Allow None or empty string
        if not v or (isinstance(v, str) and v.strip() == ""):
            return None
        
        # If provided, check extension
        allowed_ext = (".jpg", ".jpeg", ".png", ".webp", ".gif")
        if not any(str(v).lower().endswith(ext) for ext in allowed_ext):
            raise ValueError("Image URL must end with .jpg, .jpeg, .png, .webp, or .gif")
        return v

# ------------------------------------------------------------------
# INPUT SCHEMAS (Farmer side)
# ------------------------------------------------------------------
class ListingCreate(ListingBase):
    """
    Schema for creating a new listing. 
    The farmer provides their desired asking price.
    Note: ai_suggested_price is NOT here because it is generated by the server.
    """
    asking_price: float = Field(..., gt=0, example=350.0, description="Farmer's desired price per KG")

class ListingUpdate(BaseModel):
    """
    Schema for updating an existing listing.
    All fields are optional to allow partial updates.
    """
    quantity_kg: Optional[float] = Field(None, gt=0)
    asking_price: Optional[float] = Field(None, gt=0)
    status: Optional[ListingStatus] = None
    harvest_date: Optional[datetime] = None

# ------------------------------------------------------------------
# OUTPUT SCHEMAS (Data going to Frontend)
# ------------------------------------------------------------------
class ListingRead(ListingBase):
    """
    Schema for returning a listing.
    Includes database-generated IDs, status, and AI insights.
    """
    id: int
    farmer_id: int
    asking_price: float
    ai_suggested_price: Optional[float] = None
    ai_price_status: Optional[str] = None
    ai_confidence: Optional[float] = None
    ai_price_direction: Optional[str] = None
    ai_market_message: Optional[str] = None
    status: ListingStatus
    created_at: datetime
    updated_at: Optional[datetime] = None

    # Pydantic v2 configuration
    model_config = ConfigDict(from_attributes=True)

# ------------------------------------------------------------------
# AI ENHANCED RESPONSE
# ------------------------------------------------------------------
class ListingAIRecommendation(BaseModel):
    """
    Specific schema for the 'Price Analysis' view on the farmer's dashboard.
    """
    listing_id: int
    suggested_price: float
    market_confidence: float = Field(..., description="AI confidence score 0.0 - 1.0")
    reasoning: str = Field(..., example="High demand in Kigali and low seasonal supply.")
    potential_buyers_count: int = 0